export const quizzPaises = [
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Brasil?",
      opcoesResposta: ['Brasília', 'Nova Iorque', 'Paris', 'São Petesburgo'],
      respostaCorreta: 'Brasília',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da França?",
      opcoesResposta: ['Madrid', 'Roma', 'Berlim', 'Paris'],
      respostaCorreta: 'Paris',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Argentina?",
      opcoesResposta: ['Buenos Aires', 'Lima', 'Santiago', 'Rio de Janeiro'],
      respostaCorreta: 'Buenos Aires',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Japão?",
      opcoesResposta: ['Seul', 'Beijing', 'Xangai', 'Tóquio'],
      respostaCorreta: 'Tóquio',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Qatar?",
      opcoesResposta: ['Montreal', 'Doha', 'Okinawa', 'Acre'],
      respostaCorreta: 'Doha',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de São Paulo?",
      opcoesResposta: ['São Paulo', 'Rio de Janeiro', 'Campina Grande', 'Fortaleza'],
      respostaCorreta: 'Ottawa',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Rússia?",
      opcoesResposta: ['Montreal', 'São Petesburgo', 'Toronto', 'Vancouver'],
      respostaCorreta: 'São Petesburgo',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Canadá?",
      opcoesResposta: ['Montreal', 'Ottawa', 'Toronto', 'Vancouver'],
      respostaCorreta: 'Ottawa',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual continente se encontra a capital do Brasil?",
      opcoesResposta: ['Antárdida', 'América', 'Europa', 'Ásia'],
      respostaCorreta: 'América',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Gabão?",
      opcoesResposta: ['Paris', 'América', 'Banjul', 'Libreville'],
      respostaCorreta: 'Libreville',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Áustria?",
      opcoesResposta: ['Viena', 'América', 'Argel', 'Nassau'],
      respostaCorreta: 'Viena',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Costa Rica?",
      opcoesResposta: ['Moroni', 'São José', 'Seul', 'Bogotá'],
      respostaCorreta: 'São José',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Coréia do Sul",
      opcoesResposta: ['Iamussucro', 'São José', 'Seul', 'Zagrebe'],
      respostaCorreta: 'Seul',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Marrocos?",
      opcoesResposta: ['Rebate', 'Malé', 'Nuaquechote', 'Zagrebe'],
      respostaCorreta: 'Rebate',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Portugal?",
      opcoesResposta: ['Nairóbi', 'Lisboa', 'Nuaquechote', 'Islamabade'],
      respostaCorreta: 'Lisboa',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital do Reino Unido?",
      opcoesResposta: ['Londres', 'Lisboa', 'Lima', 'Assunção'],
      respostaCorreta: 'Londres',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Singapura?",
      opcoesResposta: ['Belgrado', 'Lisboa', 'Singapura', 'Dacar'],
      respostaCorreta: 'Singapura',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Senegal?",
      opcoesResposta: ['Basseterre', 'Dacar', 'Singapura', 'Apia'],
      respostaCorreta: 'Dacar',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da República Checa?",
      opcoesResposta: ['Praga', 'Dacar', 'Londres', 'Bisqueque'],
      respostaCorreta: 'Praga',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Madagáscar?",
      opcoesResposta: ['Praga', 'Antananarivo', 'Lilôngue', 'Bisqueque'],
      respostaCorreta: 'Antananarivo',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Luxemburgo?",
      opcoesResposta: ['Bamaco', 'Luxemburgo', 'Valeta', 'Bisqueque'],
      respostaCorreta: 'Luxemburgo',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital de Israel?",
      opcoesResposta: ['Bamaco', 'Jerusalém', 'Dublim', 'Bagdade'],
      respostaCorreta: 'Jerusalém',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual a capital da Jamaica?",
      opcoesResposta: ['Bamaco', 'Jerusalém', 'Kingston', 'Jibuti'],
      respostaCorreta: 'Kingston',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual é a capital da Índia?",
      opcoesResposta: ['Nova Deli', 'Jerusalém', 'Mumbai', 'Jibuti'],
      respostaCorreta: 'Nova Deli',
    },
    {
      tema: "Paises e Capitais",
      pergunta: "Qual é a capital da Alemanha?",
      opcoesResposta: ['Nova Deli', 'Hamburgo', 'Berlim', 'Mumbai'],
      respostaCorreta: 'Berlim',
    },
];
  
  