export const quizzSport = [
    {
      tema: "Esportes",
      pergunta: "Quantos jogadores ficam em campo no futebol?",
      opcoesResposta: [11, 6, 7, 8],
      respostaCorreta: 11,
    },
    {
      tema: "Esportes",
      pergunta: "Quantas cores de cartões são utilizadas em campo?",
      opcoesResposta: [4, 6, 3, 8],
      respostaCorreta: 3,
    },
    {
      tema: "Esportes",
      pergunta: "Qual seleção tem mais títulos mundiais?",
      opcoesResposta: ['Alemanha', 'China', 'Itália', 'Brasil'],
      respostaCorreta: 'Brasil',
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o esporte que utiliza uma rede e uma bola, sendo jogado em quadra dividida por uma rede no meio?",
      opcoesResposta: ['Tênis', 'Futebol', 'Vôlei', 'Basquete'],
      respostaCorreta: 'Vôlei',
    },
    {
      tema: "Esportes",
      pergunta: "Em que esporte os atletas deslizam em um gelo liso e lançam pedras em direção a um alvo circular?",
      opcoesResposta: ['Hóquei no Gelo', 'Curling', 'Patinagem Artística', 'Esqui Alpino'],
      respostaCorreta: 'Curling',
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o esporte que envolve o uso de um taco para acertar uma bola em buracos em um campo?",
      opcoesResposta: ['Tênis', 'Golfe', 'Críquete', 'Beisebol'],
      respostaCorreta: 'Golfe',
    },
    {
      tema: "Esportes",
      pergunta: "Quantas voltas um atleta deve dar em uma pista de 400 metros para completar uma corrida de 1.600 metros?",
      opcoesResposta: [1, 2, 3, 4],
      respostaCorreta: 4,
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o esporte que é jogado com um disco voador em um campo repleto de obstáculos?",
      opcoesResposta: ['Frisbee', 'Tênis de Mesa', 'Rugby', 'Atletismo'],
      respostaCorreta: 'Frisbee',
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o nome do esporte em que os atletas saltam sobre obstáculos com uma vara flexível?",
      opcoesResposta: ['Salto com Vara', 'Salto Triplo', 'Salto em Distância', 'Salto em Altura'],
      respostaCorreta: 'Salto com Vara',
    },
    {
      tema: "Esportes",
      pergunta: "Em que esporte os jogadores usam raquetes para rebater uma bola sobre uma rede?",
      opcoesResposta: ['Badminton', 'Tênis de Mesa', 'Tênis', 'Squash'],
      respostaCorreta: 'Tênis',
    },
    {
      tema: "Esportes",
      pergunta: "Quando foi fabricada a primeira Bola de Vôlei?",
      opcoesResposta: [1900, 1945, 1718, 1874],
      respostaCorreta: 1900,
    },
    {
      tema: "Esportes",
      pergunta: "Qual país tem mais título na fórmula 1?",
      opcoesResposta: ['Brasil', 'Alemanha', 'Argentina', 'França'],
      respostaCorreta: 'Alemanha',
    },
    {
      tema: "Esportes",
      pergunta: "Qual país têm mais títulos de copa américa?",
      opcoesResposta: ['Brasil', 'Alemanha', 'Argentina', 'França'],
      respostaCorreta: 'Argentina',
    },
    {
      tema: "Esportes",
      pergunta: "Em que ano o voleibol entrou nos jogos olímpicos?",
      opcoesResposta: [1930, 1964, 2006, 1900],
      respostaCorreta: 1964,
    },
    {
      tema: "Esportes",
      pergunta: "Quando foi criado o basquete?",
      opcoesResposta: [1940, 1964, 1891, 2001],
      respostaCorreta: 1891,
    },
    {
      tema: "Esportes",
      pergunta: "Em que esporte os jogadores tentam acertar uma bola em um buraco com o menor número de tacadas possível??",
      opcoesResposta: ["Golfe", "Tênis", "Críquete", "Beisebol"],
      respostaCorreta: "Golfe",
    },
    {
      tema: "Esportes",
      pergunta: "Qual esporte envolve atirar uma flecha em direção a um alvo para marcar pontos?",
      opcoesResposta: ["Golfe", "Esgrima", "Luta livre", "Tiro com arco"],
      respostaCorreta: "Tiro com arco",
    },
    {
      tema: "Esportes",
      pergunta: "Qual esporte envolve atirar uma flecha em direção a um alvo para marcar pontos?",
      opcoesResposta: ["Golfe", "Esgrima", "Luta livre", "Tiro com arco"],
      respostaCorreta: "Tiro com arco",
    },
    {
      tema: "Esportes",
      pergunta: "Qual esporte de equipe é jogado com uma bola oval e é muito popular nos Estados Unidos?",
      opcoesResposta: ["Futebol", "Rúgbi", "Futebol americano", "Tiro com arco"],
      respostaCorreta: "Futebol americano",
    },
    {
      tema: "Esportes",
      pergunta: "Quem é o artilheiro de todos os tempos da Copa do Mundo, com 16 gols em torneios da FIFA?",
      opcoesResposta: [" Miroslav Klose", " Cristiano Ronaldo", "Pelé", " Diego Maradona"],
      respostaCorreta: " Miroslav Klose",
    },
    {
      tema: "Esportes",
      pergunta: "Quantas seleções nacionais participaram da primeira Copa do Mundo em 1930?",
      opcoesResposta: [12, 16, 20, 32],
      respostaCorreta: 12,
    },
    {
      tema: "Esportes",
      pergunta: "Qual país venceu a Copa do Mundo de 2006, que foi realizada na Alemanha?",
      opcoesResposta: ["Espanha", "Argentina", "Itália", "Brasil"],
      respostaCorreta: "Itália",
    },
    {
      tema: "Esportes",
      pergunta: "Qual país conquistou a Copa do Mundo de 1966, sediada na Inglaterra?",
      opcoesResposta: ["Espanha", "Inglaterra", "Itália", "Brasil"],
      respostaCorreta: "Inglaterra",
    },
    {
      tema: "Esportes",
      pergunta: "Em qual ano a primeira Copa do Mundo de futebol feminino foi realizada?",
      opcoesResposta: [1980, 2022, 2002, 1991],
      respostaCorreta: 1991,
    },
    {
      tema: "Esportes",
      pergunta: "Em que ano o Brasil sediou sua primeira Copa do Mundo?",
      opcoesResposta: [1910, 2022, 1950, 1930],
      respostaCorreta: 1950,
    },
    {
      tema: "Esportes",
      pergunta: "Qual país sediou a primeira Copa do Mundo de futebol em 1930?",
      opcoesResposta: ["Brasil", "Uruguai", "Alemanha", "Argentina"],
      respostaCorreta: "Uruguai",
    },
    {
      tema: "Esportes",
      pergunta: "Quantos toques um time tem para passar a bola para o campo adversário após um saque?",
      opcoesResposta: ["1 toque", "2 toques", "3 toques", "7 toques"],
      respostaCorreta: "3 toques",
    },
    {
      tema: "Esportes",
      pergunta: "Qual é a altura oficial da rede de voleibol masculino?",
      opcoesResposta: ["2,20 metros", "3,60 metros", "2,60 metros", " 2,40 metros"],
      respostaCorreta: " 2,40 metros",
    },
    {
      tema: "Esportes",
      pergunta: "Como é chamado o movimento em que um jogador pula para bloquear um ataque do time adversário?",
      opcoesResposta: ["Bloqueio", "Cortada", "Saque", "Levantamento "],
      respostaCorreta: "Bloqueio",
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o evento esportivo que ocorre a cada quatro anos e reúne atletas de todo o mundo para competir em várias modalidades esportivas?",
      opcoesResposta: ["Jogos Olímpicos", "Copa do Mundo", "Super Bowl", "Campeonato Mundial"],
      respostaCorreta: "Jogos Olímpicos",
    },
    {
      tema: "Esportes",
      pergunta: "Qual país é famoso por seu desfile de abertura com uma grande delegação de atletas vestidos com trajes tradicionais?",
      opcoesResposta: ["Estados Unidos", "China", "Japão", "França"],
      respostaCorreta: "Estados Unidos",
    },
    {
      tema: "Esportes",
      pergunta: "Quem é a atual detentora do recorde de mais gols marcados em uma única edição da Copa do Mundo Feminina da FIFA, com 17 gols em 2019?",
      opcoesResposta: ["Mia Hamm", "Birgit Prinz", "Marta", "Alex Morgan"],
      respostaCorreta: "Alex Morgan",
    },
    {
      tema: "Esportes",
      pergunta: "Qual seleção nacional é conhecida 'como As Sereias do Futebol' e é famosa por suas conquistas no futebol feminino?",
      opcoesResposta: ["Estados Unidos", "Brasil", "França", "Alemanha"],
      respostaCorreta: "França",
    },
    {
      tema: "Esportes",
      pergunta: "Quem foi a primeira mulher a escalar o Monte Everest, a montanha mais alta do mundo?",
      opcoesResposta: ["Junko Tabei", "Amelia Earhart", "Serena Williams", "Maria Sharapova"],
      respostaCorreta: "Maria Sharapova",
    },
    {
      tema: "Esportes",
      pergunta: "Qual é a duração de um jogo de futsal masculino, dividido em dois tempos?",
      opcoesResposta: ["45 minutos cada tempo", "20 minutos cada tempo", "30 minutos cada tempo", "40 minutos cada tempo"],
      respostaCorreta: "20 minutos cada tempo",
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o número máximo de substituições permitidas em uma partida de futsal masculino?",
      opcoesResposta: ["5 substituições", "7 substituições", "9 substituições", "15 substituições"],
      respostaCorreta: "7 substituições",
    },
    {
      tema: "Esportes",
      pergunta: "Qual é o tamanho oficial da quadra de futsal masculino, em metros?",
      opcoesResposta: ["38 x 18", "48 x 25", "18 x 18", "40 x 20"],
      respostaCorreta: "40 x 20",
    },
  ];
  